version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    depends_on:
      - node-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    container_name: mongodb-server
    image: mongo:latest
    volumes:
      - mongo-db:/data/db

  redis:
    container_name: redis-server
    image: redis:latest
    command: redis-server --requirepass grocerycached

volumes:
  mongo-db:
