version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  node_app:
    build:
      context: .
      args:
        APP_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - APP_ENV=development
      - MONGO_USER=defaultdb
      - MONGO_PASSWORD=defaultdbpass
      - JWT_SECRET=3yVz2prs83qXxjdFJZiKEUYmoKz6aN24DDgyF4OK
      - JWT_EXPIRATION=1h
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=defaultdb
      - MONGO_INITDB_ROOT_PASSWORD=defaultdbpass
